# Generated by Django 5.2.8 on 2025-11-17 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True)),
                ('golongan_darah', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, null=True)),
                ('rhesus', models.CharField(blank=True, choices=[('Positif', 'Positif'), ('Negatif', 'Negatif')], max_length=8, null=True)),
                ('nik_ktp', models.CharField(blank=True, max_length=16, null=True)),
                ('alamat_rumah', models.TextField(blank=True, null=True)),
                ('rt_rw', models.CharField(blank=True, max_length=10, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kab_kota', models.CharField(blank=True, max_length=100, null=True)),
                ('pekerjaan', models.CharField(blank=True, choices=[('TNI', 'TNI'), ('POLRI', 'POLRI'), ('ASN', 'ASN'), ('BUMN', 'BUMN'), ('Mahasiswa', 'Mahasiswa'), ('Pelajar', 'Pelajar'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Petani', 'Petani'), ('Buruh', 'Buruh'), ('Nelayan', 'Nelayan'), ('Wiraswasta', 'Wiraswasta'), ('Lain-lain', 'Lain-lain')], max_length=100, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('tgl_donor_terakhir', models.DateField(blank=True, null=True)),
                ('tgl', models.DateField(auto_now_add=True)),
                ('waktu', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_sehat_hari_ini', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q2_minum_obat', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3a_diabetes', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3b_ginjal', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3c_gangguan_darah', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3d_malaria', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3e_ashma', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3f_alergi', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3g_tbc', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3h_hepatitis', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q3i_jantung', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q4_pingsan_kejang', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q5_gejala_hiv', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q6_tindik_tato', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q7_keluar_daerah', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q8_cabut_gigi', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q9_identitas_lain', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q10_donor_kurang_3_bulan', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('q11_wanita_kondisi', models.CharField(blank=True, choices=[('Iya', 'Iya'), ('Tidak', 'Tidak')], max_length=5, null=True)),
                ('hb', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Rendah', 'Rendah'), ('Tinggi', 'Tinggi')], max_length=10, null=True)),
                ('hb_value', models.FloatField(blank=True, null=True)),
                ('berat_badan', models.FloatField(blank=True, null=True)),
                ('suhu_badan', models.FloatField(blank=True, null=True)),
                ('tensi', models.CharField(blank=True, max_length=10, null=True)),
                ('nadi', models.IntegerField(blank=True, null=True)),
                ('alasan_tidak_layak', models.TextField(blank=True, null=True)),
                ('keputusan_petugas', models.CharField(blank=True, max_length=20, null=True)),
                ('catatan_dokter', models.TextField(blank=True, null=True)),
                ('nama_petugas', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('nomor_kantong', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_donasi', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_donor', models.CharField(blank=True, max_length=20, null=True)),
                ('jenis_kantong', models.CharField(blank=True, max_length=20, null=True)),
                ('pengambilan', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_cc', models.IntegerField(blank=True, null=True)),
                ('diambil_sebanyak', models.CharField(blank=True, max_length=20, null=True)),
                ('reaksi_donor', models.TextField(blank=True, null=True)),
                ('pendonor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pendonor')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.petugas')),
            ],
        ),
    ]
