# Generated by Django 5.2.8 on 2025-11-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifikasi',
            name='petugas_aftap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifikasi_aftap', to='myapp.petugas'),
        ),
    ]
