# Generated by Django 5.2.8 on 2025-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_verifikasi_petugas_aftap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifikasi',
            name='reaksi_donor',
            field=models.CharField(blank=True, choices=[('Tidak Ada', 'Tidak Ada'), ('Pusing', 'Pusing'), ('Pingsan', 'Pingsan'), ('Bocor', 'Bocor'), ('Mual', 'Mual'), ('Kram', 'Kram'), ('Lainnya', 'Lainnya')], max_length=50, null=True),
        ),
    ]
