# Generated by Django 5.2.8 on 2025-11-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_verifikasi_reaksi_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifikasi',
            name='is_manual_input',
            field=models.BooleanField(default=False),
        ),
    ]
